version: '1.0.0'
services:
  nestjs:
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    image: api-whatsapp:1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports: 
      - 3003:3003