version: '1.0.1'

services:
  nestjs:
    container_name: whatsapp_api 
    environment:
      - CELL_NUMBER
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports: 
      - 3003:3003
    volumes:
      - /server/node_modules
    restart: always
